### ISSUE TITLE
how can we change the font file on the fly?

### ISSUE THREAD

**Issue by moebiussurfing** [armadillu/ofxFontStash#29]
I see that setup can be only be called once.
There's the addFont method but I don't know how to select after added.
There's some way to clear the font and load another one?

**Comment by armadillu** [comment]
drawMultiColumnFormatted() allows mixing fonts, sizes and colors. Look at the example, and [here](https://github.com/armadillu/ofxFontStash/blob/master/src/ofxFontStash.h#L95) you specify fonts with @1, @2, etc where the number is dictated by the order in whic you setup() and addFont()-
It's note quite finished.

Otherwise I recommend you keep around different ofxFontStash objects, each setup with the font you need, or just destroy your current fontstash and setup again

```
ofxFontStash font;
font.setup("myFont.ttf");
font.draw()
....
font = ofxFontStash();
font.setup("myFont2.ttf");
font.draw()
```
